# Utiliza a imagem base do OpenJDK
FROM openjdk:17-jdk-slim

# Instala o Maven
RUN apt-get update && apt-get install -y maven

# Configuração do diretório de trabalho
WORKDIR /app

# Copia o arquivo pom.xml e qualquer outro arquivo necessário para resolver dependências
COPY pom.xml /app
COPY src /app/src

# Compila o projeto (baixa dependências)
RUN mvn dependency:resolve

# Define o comando de entrada para executar o Spring Boot
ENTRYPOINT ["mvn", "spring-boot:run"]
