# Utiliza a imagem base do OpenJDK
FROM openjdk:17-jdk-slim

# Instala o Maven
RUN apt-get update && apt-get install -y maven

# Configuração do diretório de trabalho
WORKDIR /app

# Copia o código-fonte para o contêiner
COPY . /app

# Compila o projeto
RUN mvn clean package -DskipTests

# Define o comando de entrada
ENTRYPOINT ["java", "-jar", "target/finance-0.0.1-SNAPSHOT.jar"]
